SELECT 
    ugb.TITLE AS 게시글제목,
    ugb.BOARD_ID AS 게시글ID,
    ugr.REPLY_ID AS 댓글ID,
    ugr.WRITER_ID AS 댓글작성자ID,
    ugr.CONTENTS AS 댓글내용,
    DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') AS 댓글작성일
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_REPLY ugr ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE ugr.CREATED_DATE >= '2022-10-01'
  AND ugr.CREATED_DATE < '2022-11-01' or ugb.CREATED_DATE >= '2022-10-01'
  AND ugb.CREATED_DATE < '2022-11-01'
ORDER BY ugr.CREATED_DATE ASC, ugb.TITLE ASC;